configfile: "config/config.yml"

include: "rules/0-coexpression.smk"
include: "rules/1-coexpression_plot.smk"
include: "rules/1-coexpression_corrected_counts.smk"

include: "rules/0-silhouette.smk"
include: "rules/1-silhouette_plot.smk"

include: "rules/0-embedding.smk"
include: "rules/1-embedding_plot.smk"

include: "rules/0-ovrlpy.smk"
include: "rules/0-resolvi.smk"


rule all:
    input:
        rules.silhouette_all.input,
        rules.silhouette_plot_all.input,
        rules.embed_condition_all.input,
        rules.embed_condition_plot_all.input,
        rules.embed_panel_plot_all.input,
        rules.embed_panel_all.input,
        rules.resolvi_all.input,
        rules.coexpression_all.input,
        rules.ovrlpy_all.input,
        rules.coexpression_plot_all.input,
