base_dir: "/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/xenium_paper/"
data_dir: "data/"
scratch_dir: "scratch/"
scripts_dir: "scripts/"
results_dir: "results/"
figures_dir: "figures/"
log_dir: "log/"
markers_dir: "data/markers/"

xenium_raw_data_dir: "data/xenium/raw/"
xenium_processed_data_dir: "data/xenium/processed/segmentation/"
scrnaseq_processed_data_dir: "data/scRNAseq/processed/"
visium_raw_data_dir: "data/visium/raw/"
visium_processed_data_dir: "data/visium/processed/"
