base_dir: "/work/PRTNR/CHUV/DIR/rgottar1/spatial/env/xenium_paper/"
data_dir: "data/"
scratch_dir: "workflow/scratch/"
scripts_dir: "workflow/scripts/"
results_dir: "results/"
figures_dir: "figures/"
log_dir: "log/"
markers_dir: "data/markers/"

xenium_metadata_dir: "data/xenium/metadata/"
xenium_raw_data_dir: "data/xenium/raw/"
xenium_processed_data_dir: "data/xenium/processed/segmentation/"
xenium_std_seurat_analysis_dir: "data/xenium/processed/std_seurat_analysis/"
# xenium_cell_type_annotation_dir: "data/xenium/processed/cell_type_annotation/"
xenium_cell_type_annotation_dir: "data/xenium/_backups/_processed_problematic_matched_combo/cell_type_annotation/"

scrnaseq_processed_data_dir: "data/scRNAseq/processed/"
visium_raw_data_dir: "data/visium/raw/"
visium_processed_data_dir: "data/visium/processed/"

umap_n_comps: 50
umap_n_neighbors: 50
umap_min_dist: 0.5
umap_metric: 'euclidean'
